resources:
  repositories:
  - repository: MyAzureReposGitRepository # In a different organization
    endpoint: v-mazayt-org
    type: git
    name: TestProject/TestGit

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

