trigger:
- None

pool:
  name: MultipleAgentsOnOneHost

stages:
- template: Template.yml
  parameters:
    appFolders: [
      'app',
      'app2'
    ]
    selectVersions: [
      {
        versionName: '15_4',
        Container: {
          containerName: 'test154',
          Imagename: '15-4-de-onprem',
          Major: 15,
          Minor: 4,
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '15_de_latest',
        Container: {
          containerName: 'test15dl',
          Imagename: '15-de-onprem-latest',
          Major: 15,
          Minor: '',
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '16_1',
        Container: {
          containerName: 'test161',
          Imagename: '16-1-de-onprem',
          Major: 16,
          Minor: 1,
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '16_de_latest',
        Container: {
          containerName: 'test16dl',
          Imagename: '16-de-onprem-latest',
          Major: 16,
          Minor: '',
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '17_0',
        Container: {
          containerName: 'test170',
          Imagename: '17-0-de-onprem',
          Major: 17,
          Minor: 0,
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '17_de_latest',
        Container: {
          containerName: 'test17dl',
          Imagename: '17-de-onprem-latest',
          Major: 17,
          Minor: '',
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '18_0',
        Container: {
          containerName: 'test180',
          Imagename: '18-0-de-onprem',
          Major: 18,
          Minor: 0,
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '18_de_latest',
        Container: {
          containerName: 'test18dl',
          Imagename: '18-de-onprem-latest',
          Major: 18,
          Minor: '',
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '19_0',
        Container: {
          containerName: 'test190',
          Imagename: '19-0-de-onprem',
          Major: 19,
          Minor: 0,
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        },
        AppJSON: {
          showMyCode: false
        }
      },
      {
        versionName: '19_de_latest',
        Container: {
          containerName: 'test19dl',
          Imagename: '19-de-onprem-latest',
          Major: 19,
          Minor: '',
          Country: 'de',
          target: 'OnPrem',
          storageAccount: ''
        }
      }
    ]